apiVersion: v1
kind: Service
metadata:
  name: {{ include "yt-clone.fullname" . }}-backend
  labels:
    {{- include "yt-clone.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yt-clone.selectorLabels" . | nindent 4 }}
    component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yt-clone.fullname" . }}-frontend
  labels:
    {{- include "yt-clone.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yt-clone.selectorLabels" . | nindent 4 }}
    component: frontend
