apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: yt-clone
  labels:
    app: backend
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
      - name: backend
        image: yt-clone-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: PORT
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: JWT_EXPIRES_IN
        - name: VERIFICATION_TOKEN_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: VERIFICATION_TOKEN_EXPIRES_IN
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: SMTP_PORT
        - name: SMTP_SECURE
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: SMTP_SECURE
        - name: DB_SSL
          valueFrom:
            configMapKeyRef:
              name: yt-clone-config
              key: DB_SSL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: JWT_SECRET
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: DB_PASSWORD
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: SMTP_PASS
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: DB_USER
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: yt-clone-secrets
              key: FRONTEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yt-clone
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
