apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-clone-config
  namespace: yt-clone
data:
  NODE_ENV: "production"
  PORT: "3000"
  JWT_EXPIRES_IN: "7d"
  VERIFICATION_TOKEN_EXPIRES_IN: "24h"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  DB_SSL: "true"
  VITE_API_URL: "http://backend-service:3000"
