-- Add columns to Post table
ALTER TABLE "Post" ADD COLUMN "thumbnail_url" TEXT;
ALTER TABLE "Post" ADD COLUMN "description" TEXT;
ALTER TABLE "Post" ADD COLUMN "views" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN "likes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN "dislikes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN "duration" TEXT;
